
# ================================== TRANSLATIONS ==================================
# Custom languages/variations can be added with ease, just copy and paste a language, change the name, and edit the text such as customizing the "Breach" to wither has ben deded
# Custom languages will not show up in /blanguage's tab complete, just set the "language" section to the name of your new language EXAMPLE- language: customlanguage
language: english
translation:
  english:
    breach: The death of the Undead Wither unleashes its raw power into the worlds, breaking the seal between the overworld and nether world.
    breachsa: A gemstone has been sacrificed to the gods!
    breachend: The breach between the overworld and nether world has been sealed!
    magmas: A feiry deity enters the overworld attracted by a dark power
    cursedlore: Eradicates energy
    ichorlore: The dryed blood of gods.
    ichorsticklore: A handle made of solid Ichor
    ichorswordlore: A sword made of the gods blood.
    ichorchestlore: A chestplate made of the gods blood.
    ichorleglore: Leggings made of the gods blood.
    ichorbootlore: Boots made of the gods blood.
    ichorhelmlore: A helmet made of the gods blood.
    booklore0: A mysterious book emitting dark power
    booklore1: May contain ancient spoils
    forgelore: An forged based on an ancient design.
    totem_lore: Bring to a rift
    token_lore: Bring to a villager
  norsk:
    breach: Withers død slipper løs sin rå kraft inn i verdenene, og bryter selet mellom oververdenen og den andre verden.
    booklore0: En mystisk bok som avgir mørk kraft
    booklore1: Kan inneholde gamle spoils
    breachsa: En edelsten er blitt ofret til gudene!
    breachend: Bruddet mellom oververden og  underverden er blitt forseglet!
    magmas: En brennende guddom kommer inn i oververdenen tiltrukket av en mørk kraft
    cursedlore: Utretter energi
    ichorlore: Det tørkede blodet fra guder.
    ichorsticklore: Et håndtak laget av solid Ichor.
    ichorswordlore: Et sverd laged av guds blod.
    ichorchestlore: Et brystplate laged av guds blod.
    ichorleglore: Beinplater laged av guds blod.
    ichorbootlore: støvlar laged av guds blod.
    ichorhelmlore: Et hjelm laged av guds blod.
    forgelore: An forged based on an ancient design.
    totem_lore: Et totem som åpner en rift inn i overherrens hjem
    token_lore: 
  español:
    breach: La muerte de Wither libera su fuerza bruta en los mundos, rompiendo el sello entre el mundo y el otro mundo.
    breachsa: Una piedra preciosa ha sido sacrificada a los dioses!
    breachend: La brecha entre el mundo superior y el inframundo ha sido sellada!
    magmas: Una deidad ardiente viene al mundo atraída por una fuerza oscura.
    cursedlore: Crea energía
    ichorlore: La sangre seca de los dioses.
    ichorsticklore: Un mango hecho de Ichor sólido.
    ichorswordlore: Una espada hecha de la sangre de Dios.
    ichorchestlore: Un pechera hecha de la sangre de Dios.
    ichorleglore: Grebas hecha de la sangre de Dios.
    ichorbootlore: Botas hecha de la sangre de Dios.
    ichorhelmlore: Yelmo hecha de la sangre de Dios.
    booklore0: Un libro misterioso que emite fuerza oscura.
    booklore1: Puede contener Botines viejos.
    forgelore: An forged based on an ancient design.
    totem_lore: Traer al rift
    token_lore: Traer al aldeano
  customlanguage:
    breach: wither has ben deded
    booklore0: coolio booko
    booklore1: masterious
    breachsa: a cool gem was eaten by a blackhole!
    breachend: the breach has been fixed with a bandaid!
    magmas: A big fire thing wants to kill everyone!
    cursedlore: this thing is cursed! watch out!
    ichorlore: blud
    ichorsticklore: bloody stick
    ichorswordlore: blood sword of yellowness

# ================================== SCALES ==================================

damage_scale:
  tier0:
    cow: 3
    pig: 3
    sheep: 3
  tier1:
    drowned: 4
    skeleton: 4
    zombie: 4
  tier2:
    blaze: 5
    guardian: 5
    stray: 5
    creeper: 5
  tier3:
    guardian_elder: 5
    skeleton_wither: 5
  vex: 1
  addon:
    nordic:
      warlock: 2
  
health_scale:
  tier0:
    cow: 1
    phantom: 1
    pig: 1
    sheep: 1
    tropic: 5
  tier1:
    drowned: 1
    skeleton: 1
    zombie: 1
  tier2:
    blaze: 1
    creeper: 1
    guardian: 1
    stray: 1
  tier3:
    guardian_elder: 1
    skeleton_wither: 1
  tier4:
    dragon: 1
    wither: 1
  tier5:
    magma: 1
  vex: 1
  raids:
    ghast: 60
  addon:
    nordic:
      warlock: 2
enchants:
  lifesteal: 0.1
  bleed:  0.33333333333
#enchants.bleed is how many bleedticks to add
# raids.ghast is ghasts default health mulitplied by number (Ghasts have low health)

# ================================== SPAWNRATES ==================================
# Creeper spawnrates do not change
spawnrates:
  tier0spawnrate: 0.1
  tier1spawnrate: 0.01
  tier2spawnrate: 0.005
  tier3spawnrate: 0.005
  fish: 0.01
  vex: 0.1
  merchants:
    special_traders_enabled: true
    rate: 0.3
    merchant:
      enabled: true
    nomadic_tinker:
      enabled: true

# ================================== BOSS CONFIG ==================================
bosses:
  has_glow: true
  smite_death: true
  show_bar: 30
  show_tier_in_bar: false
  bar_enabled: true
  vex: true
  undead_wither:
    radius: 10
    level: 3
    effect_enabled: true
  phantom:
    effect_enabled: true
  custom_loot_pools:
    tier0: false
    tier1: false
    tier2: false
    tier3: false
    tier4: false
    tier5: false
    ghast_raid: false
    addon:
      nordic:
        fenrir: false
        warlock: false
  enabled_bosses:
    cow: true
    pig: true
    sheep: true
    drowned: true
    skeleton: true
    zombie: true
    blaze: true
    creeper: true
    guardian: true
    stray: true
    guardian_elder: true
    slime: true
    skeleton_wither: true
    dragon: true
    wither: true
    magma: true
    fenrir: true

# ================================== Events ==================================

breach:
  max: 5
  amount: 0

ghastevent:
  active: false
# Change only if ghastraid does not start when rightclicking gateway block with ghast_totem

raids:
  gladiator:
    active: false
    specialblocks:
      beacon_glass:
        ==: org.bukkit.Location
        world: MoreBosses-Colosseum
        x: 8.4551483700261
        y: 4.0
        z: 8.522993742351828
        pitch: 86.59607
        yaw: 181.73213
    spawns:
      king:
        ==: org.bukkit.Location
        world: MoreBosses-Colosseum
        x: 8.574518792980488
        y: 10.5
        z: 41.93660153325716
        pitch: 6.728375
        yaw: -180.37415
      gate1:
        ==: org.bukkit.Location
        world: MoreBosses-Colosseum
        x: 8.538859337073339
        y: 4.875
        z: 37.325580890865155
        pitch: 0.9304752
        yaw: -179.77246
      gate2:
        ==: org.bukkit.Location
        world: MoreBosses-Colosseum
        x: -20.370532266775484
        y: 4.875
        z: 8.533264889852719
        pitch: 0.6468218
        yaw: -89.85193
      gate3:
        ==: org.bukkit.Location
        world: MoreBosses-Colosseum
        x: 37.57164505447856
        y: 4.875
        z: 8.502478792202451
        pitch: -0.20416181
        yaw: -270.54395
  ghast_raid:
    ==: org.bukkit.Location
    world: MoreBosses-void
    x: 0.29412187793998235
    y: 168.85952724300694
    z: 30.361163485952446
    pitch: 48.142868
    yaw: 185.52869
  ghast_raid_minion_spawns:
    '1':
      ==: org.bukkit.Location
      world: MoreBosses-void
      x: 21.41898116497156
      y: 162.0
      z: 12.349618076959192
      pitch: 90.0
      yaw: 182.43951
    '2':
      ==: org.bukkit.Location
      world: MoreBosses-void
      x: -2.96773881878915
      y: 162.0
      z: -5.54990324595229
      pitch: 35.400265
      yaw: -196.76314
    '3':
      ==: org.bukkit.Location
      world: MoreBosses-void
      x: 25.952250525345075
      y: 161.0
      z: -9.224853848404239
      pitch: 49.0503
      yaw: 82.38677
    '4':
      ==: org.bukkit.Location
      world: MoreBosses-void
      x: -0.4823046572372496
      y: 153.0
      z: 14.290684163411193
      pitch: 46.350296
      yaw: -233.51256
  teleports:
    ghast:
      '1':
        ==: org.bukkit.Location
        world: MoreBosses-void
        x: -22.11812122144501
        y: 166.05369363891091
        z: -15.763348184485839
        pitch: 44.455276
        yaw: 302.11334
      '2':
        ==: org.bukkit.Location
        world: MoreBosses-void
        x: 36.290793575731115
        y: 166.05369363891091
        z: -24.18448504461469
        pitch: 35.66179
        yaw: 49.62079
      '3':
        ==: org.bukkit.Location
        world: MoreBosses-void
        x: 38.344643175111024
        y: 166.05369363891091
        z: 23.81790238099832
        pitch: 37.931076
        yaw: 132.16614
#/bsetspawn to set spawn to players current location Permission: "bosses.raid.ghastspawn"
# ================================== OTHER ==================================

enabled_enchants:
  replenish: true
  mites: true
  lifesteal: true
  ember: true
  undying: true
  smelt: true
  fleet: true

world:
  disable_phantoms: false
  keep_inventory: false
  addons:
    nordic:
      nether_world: true

tier0_bosses:
  phantomboss_enabled: true
  fishboss_enabled: true


experimental:
  Gems: true


rewards:
  Spoils: true

tier4_bosses:
  enabled: true
  Enderdragon_Killed: false
  Wither_Killed: false
  Undeaddragon_Killed: false
  Undeadwither_Killed: false

# ================================= Reload =====================================
# Allows plugin to be compatible with /reload or /rl
reload:
  reload_permission: "bukkit.command.reload"
