name: MoreBosses
<<<<<<< Updated upstream
version: TEST_VERSION_r.2.3.4
=======
version: r.2.3.4
>>>>>>> Stashed changes
author: Derpy
main: me.Derpy.Bosses.MoreBosses
description: Adds more bosses to your game!
api-version: 1.14
softdepend: [NordicReload]

commands:
  bspawn:
    description: Spawns Random Bosses mobs
    usage: bspawn <Mob>
  bdebug:
    description: "Debug certain elements"
    usage: debug <arg>
  bevent:
    description: "Toggle world events"
    usage: bevent <arg> <arg>
  blanguage:
    description: "Plugin Language (Reloads server)"
    usage: blanguage <language>
  barena:
    description: "Teleport to a boss arena"
    usage: barena <arena>
  bsetspawn:
    description: "Set the spawn location of an arena mob"
    usage: bsetspawn <mob>
  bsaveworld:
    description: "Saves the current world the user is in (Used for boss arenas)"
    usage: bsaveworld
  blootpool:
    description: "Edit custom drop pools"
    usage: blootpool <pool>